### ISSUE TITLE
Test for Float.NaN uses == instead of Float.isNaN(x).

### ISSUE THREAD

**Issue by scuniff** [fiji/Fiji_Plugins#6]
Test for Float.NaN uses == instead of Float.isNaN(x).

CircleFitter.java(https://github.com/fiji/Fiji_Plugins/blob/master/src/main/java/fiji/util/Circle_Fitter.java)

Line 140
	if (ip==null || **threshold == Float.NaN)** { return null; }

should be ?
	if (ip==null || **Float.isNaN(threshold))** { return null; }

See:
https://docs.oracle.com/javase/specs/jls/se7/html/jls-15.html#jls-15.20.1

**15.20.1. Numerical Comparison Operators <, <=, >, and >=**
...
....
....
The result of a floating-point comparison, as determined by the specification of the IEEE 754 standard, is:
•	If either operand is NaN, then the result is false.

**Comment by ctrueden** [comment]
Thanks for the report!
